name: zlib
builder:
  name: BalabitBuilder
  configure_options: "--shared"
  flags: "no-make-dist out-of-tree-build-incompatible"
platforms:
  - aix-6.1/powerpc
  - windows-2012/amd64
  - windows-2012/i386
  - linux-glibc2.11/amd64
